### ISSUE TITLE
[CI Remote for Go] iOS & Android app for Go Server

### ISSUE THREAD

**Issue by timoa** [gocd/gocd#1485]
Hi Guys!

Just a message to announce the availability in few days, of my new free iOS app to control your pipelines and agents everywhere :) I have released it to iTunes and wait the review now.

I have developed also the Android version, but I need more time to finish the assets for the Google Play.

The future releases will be awesome with the possibility to launch your pipelines when you are on the way to the coffee shop or in the transportations! 

## PIPELINES
Take a look at your current running builds with the Pipelines view

## AGENTS
See how many agents works on your builds with the Agents view

## SETTINGS
Make a backup of your Go Server config (config.xml, DB, etc.) on the fly

## DEMO MODE
If you want to test this app without your own Go Server, try the demo mode and connect to the official GO.cd build server

CI Remote for Go works on iPhone and iPad and use the new iOS9 SDK.

CI Remote is an unofficial client app for Go and consume the Go API of your server.

Let me now if you want an invitation to TestFlight to try it, I need your feedback!

You can check the design of the iOS and Android app here: https://www.pinterest.com/timoa/my-projects/

Thank you for all the contribution to GOCD!

Damien - @timoa - http://timoa.com

**Comment by srinivasupadhya** [comment]
looks awesome to me :+1:

**Comment by timoa** [comment]
Thank you @srinivasupadhya!

I also started the design of the Apple Watch app to deploy your builds on the go :)

**Comment by zabil** [comment]
Yes! Finally I have a reason to buy the watch :-)
This app looks amazing @timoa

**Comment by arvindsv** [comment]
Looks good! I wouldn't mind a TestFlight invitation.

**Comment by timoa** [comment]
@arvindsv Contact me via my website http://timoa.com and I will send you an invitation :)

Apple Beta reviewed the build this night and you can now download the current and the future releases.

**Comment by timoa** [comment]
**Update**: I built a pre-release for Android. You can now download it here:
https://www.wetransfer.com/downloads/cd2510ce6ca5633d8485e130634f074420150916100210/8f6dbd5774f152a39372d1403f4dbf6520150916100210/de7d0d

I have few fixes to finish on it before I submit it on the Play Store (Feedback can crash at close, the Android theme not used for all Windows on Android 5.0, etc.)

**Comment by timoa** [comment]
Update: The Android version is available on the Google Play Store:
https://play.google.com/store/apps/details?id=com.timoa.ciremote

Compatibility from Android 4.0 to 5.1 (6.0 in test).

I already start the next release with the details of Pipelines and the possibility to start / pause a pipeline

You can send me your feedback on Twitter @timoa / http://timoa.com and in the app (Settings => Feedback)

You can also review the app if you like it! If not, wait the next release to review it :)

Thank you for your help to promote it!

Damien

PS: iOS version is in review and probably available Monday or Tuesday.

**Comment by henriquegemignani** [comment]
Installed the android version, looks really nice and fast!
Looking forward to more development :)

**Comment by timoa** [comment]
Thank you @henriquegemignani! 

I'm already on the next release with more interaction with the pipelines (start/pause the stages) and more details :)

For a first release, you need to do a lot of non-technical things like define the design, mockups, assets for the app and the stores, etc. but next releases are more for new features!

**Comment by timoa** [comment]
The iOS version of **CI Remote for Go** is now on iTunes:
https://itunes.apple.com/us/app/ci-remote-for-go/id1031029921?ls=1&mt=8

Next release is on the pipeline :)

**Comment by alexouzounis** [comment]
Hi @timoa ! 
Great work! 
Does it support OAuth plugins like https://github.com/gocd-contrib/gocd-oauth-login ?
Alex

**Comment by timoa** [comment]
Thank you, @alexouzounis!

Currently, it doesn't support the GO plugins because the app needs to know before you log in if your server has this plugin or no before it show you the OAuth2 login option...

I can check that like I do to get the version of GO.CD: Call the login page, get the HTML and search the image that link to the OAuth2 login... I get the version in the bottom of the page, near the copyright :)

I need to see what is the impact for the Login page and how much works to do that.

Thank you for your feedback!
Damien

**Comment by alexouzounis** [comment]
Good point! 
Maybe we can update gocd to report OAuth capabilities via the API and use that to query the server prior to asking the user to input his credentials.

**Comment by timoa** [comment]
Yes, but for that, I need a public endpoint to get the capacities / features of the GO Server... because, at this point, I'm not authenticating to the server...

I will prepare a list of optimization I need on the API for the next release(s). For example, to get the list of 50 pipelines with the current status, I need to call:

1x Pipeline Group
50x Pipeline History (I just need the last one, but I get 10 => 50x JSON responses with 1900 lines)
50x Pipeline Status to get only three properties: locked, paused, schedulable
--------------------------
Total:101 calls!

For a mobile app with a bad connection, is not the best but I talked with the Go Team (Ken Mugrage and Alagu Subramani) and I will try to contribute on that.

The app is compatible from 14.3 to 15.2 and I need to prepare a new 15.3 with a lot of changes that can break the connection to this version (and also the demo mode).

**Comment by alexouzounis** [comment]
Cool. I am happy to contribute so ping me when you get things rolling and I can lend a hand :)

**Comment by timoa** [comment]
Thx @alexouzounis !

**Comment by zabil** [comment]
@timoa take a look at this https://github.com/gocd/gocd/issues/1392 to see if it'll help.

**Comment by timoa** [comment]
@zabil Sorry, I'm not really a Ruby developer... Can you explain what is the goal of this new Dashboard API endpoint? Thx

I really need to take a look to the new 15.3 API to know if I will have any issues with this version on CI Remote...

**Comment by zabil** [comment]
It exposes a new endpoint that returns data of what's currently on the dashboard.
You can see the JSON it returns here here https://github.com/gocd/gocd/pull/1205

**Comment by arvindsv** [comment]
And [here](https://github.com/gocd/gocd/issues/1485#issuecomment-144761691).

**Comment by juhijariwala** [comment]
You can find dashboard API doc [here.](http://api.go.cd/15.3.0/#get-dashboard)

**Comment by ketan** [comment]
> I will prepare a list of optimization I need on the API for the next release(s). For example, to get the list of 50 pipelines with the current status, I need to call:

@timoa - have you seen the [cctray feed](https://build.go.cd/go/cctray.xml)?

**Comment by ketan** [comment]
> @zabil Sorry, I'm not really a Ruby developer... Can you explain what is the goal of this new Dashboard API endpoint? Thx

The goal of the dashboard API endpoint is to provide *all* the information that would be needed to render the "pipelines page"(`go/pipelines`) in go. We hope that this allows users to build alternative dashboards, and apps to brief display pipeline status information.

We would like it if you to use this API from our experimental builds and submit requests to enhance it as needed.

**Comment by ketan** [comment]
> Yes, but for that, I need a public endpoint to get the capacities / features of the GO Server... because, at this point, I'm not authenticating to the server...

Would an API call to get the server version help here? If you could tell us something more specific by providing examples of APIs implemented by other application servers (not just CI/CD) or tell us what specific information you'd like from this API, we're happy to work towards a (loose) specification that somebody can implement.

**Comment by timoa** [comment]
Thank you for your answers! The dashboard API will be awesome :) 1 call rather than 101!

I need to implement this calls for the previous releases but the v15.3.0, I will create a separate library to call more optimised API endpoints.

For the version of the API, I will search how the other API works but currently, the version number is sufficient for me.

Another important endpoint I didn't find is the list of permissions of a user. The connected user is an admin? For example with the backup endpoint, I need to be admin to do that but I can't add or remove this action from my UI before I test to call it :(

If I can call an API endpoint like /me or get this information on the response of the authorization (basic auth), I can adapt my UI to the user.

**Comment by ketan** [comment]
> Thank you for your answers! The dashboard API will be awesome :) 1 call rather than 101!

15.2 (perhaps 15.1) had an undocumented api (/go/dashboard.json) that you may find useful, please note that this API no longer exists in 15.3.

> If I can call an API endpoint like /me or get this information on the response of the authorization (basic auth), I can adapt my UI to the user.

Please log an issue against the users API (A pull request would be even more awesome)

* http://api.go.cd/current/#get-one-user
* https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/app/presenters/api_v1/user_representer.rb
* https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/spec/presenters/api_v1/user_representer_spec.rb

**Comment by timoa** [comment]
Thank you @ketan for this information!

I have two questions:
1) Why is the cctray feed public?
2) Same for the /go/dashboard.json?

The /go/dashboard.json is a very good for I try to achieve on the Pipeline list! 
With this call, I get all I need to improve the performance on some devices :)

For the 15.3.0 servers, I will use the official dashboard API.

I will log an issue against the users API.

Thank you!

**Comment by ketan** [comment]
> I have two questions:
> 1) Why is the cctray feed public?

It is not public - it only shows you pipelines that you have view access to.

> 2) Same for the /go/dashboard.json?

Same as above - it only shows you the pipelines that you have view access to.

If you are a use that the server identifies correctly, but don't have access to any pipelines, the responses from these APIs will render a 200 status with a blank array of XML or JSON.

**Comment by timoa** [comment]
Hi, All!

I released a new version of CI Remote for GO (Android / iOS) this week with more views of pipeline history, stages and jobs but I have an issue with the status of the stages / jobs during a build....

I don't know the rules to say if it will fail or if a job waits for an Agent, etc...

Do we have a reference / doc, for all the status / result that a pipeline can handle? I found this one for now:
- Completed
- Passed
- Failed
- Building
- Cancelled
- Scheduled
- Unknown (need to combine the different job status/result to create the right status)

Thank you for your help :)

**Comment by arvindsv** [comment]
@timoa: The closest "reference" I can think of are the [StageState](https://github.com/gocd/gocd/blob/master/common/src/com/thoughtworks/go/domain/StageState.java#L22-L27) and [StageResult](https://github.com/gocd/gocd/blob/master/common/src/com/thoughtworks/go/domain/StageResult.java). It's still not comprehensive, because a stage is not said to be "Scheduled", but [jobs](https://github.com/gocd/gocd/blob/master/common/src/com/thoughtworks/go/domain/JobState.java#L20-L30) are.

**Comment by monikakatiyar16** [comment]
@timoa Do we have support for this mobile app for v20.1.0? The current app doesn't seem to be compatible. It doesn't authenticate with the current credentials for our v20.1.0 gocd server. Not sure if this is the right place to text, since it's quite old discussion.
We would really love to have a mobile app for the same, as it tends to be very handy!
