### ISSUE TITLE
UserHelper is retrieving the wrong LDAP attribute for username

### ISSUE THREAD

**Issue by tpbrown** [gocd/gocd#2971]
##### Issue Type

- Bug Report
##### Summary

I _think_ this is supposed to be pulling the user's (human) name and falling back to the login username if that fails.

However if the DN return already contains a CN it will return the wrong name. 
ex. uid=tpbrown,cn=users,dc=foo,dc=com

Will return "users" as the username, instead of grabbing the cn attribute from LDAP.

Additionally, if this is actually wanting the CN attribute then the pattern in resolveDisplayName() will also need updated.  Right now it's only matching if CN attribute ends with a comma then space.  Comma or space would be correct for a login userid in a DN, but comma or newline would be correct for a humans name in the CN attribute directly. 

e.g. cn=Tim Brown will not match as it is, but the above uid example above will match but not as desired.

##### Environment

16.11.0 - Linux

##### Possible Fix
change [getUserName()] (https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/util/UserHelper.java#L53) from userDetails.getDn() to userDetails.getAttributes().toString() (all attributes).

Thanks!

**Comment by arvindsv** [comment]
@bdpiparva will know better, but it looks like this is the same as the issue being fixed by [this](https://github.com/gocd/gocd/pull/2938/files#diff-c2b7df3334e2e51d523099177d637d89R95).

**Comment by tpbrown** [comment]
@arvindsv yep - definitely right in there.
@bdpiparva is displayName intended to be a login name ('tpbrown') or a person's name ('Tim Brown')?

It looks like the referenced code still uses DN, which won't work for the latter - right?

**Comment by arvindsv** [comment]
My opinion: It should be "Tim Brown". So, whatever is needed to make that work.

**Comment by bdpiparva** [comment]
@tpbrown:  @arvindsv is right. username is  "tpbrown" and displayName is "Tim Brown".  However, you can also configure the 'displayName' as per your requirement.

**Comment by PredatorVI** [comment]
I'm currently using GoCD v17.3.0 and this is still an issue for us.  Has there been any progress on this?  We are using FreeIPA which I believe is a flavor of OpenLDAP.

![image](https://cloud.githubusercontent.com/assets/1933277/24812015/aecd3f74-1b85-11e7-943f-8f4fb5657737.png)

**Comment by PredatorVI** [comment]
On a similar note, if I manually trigger a pipeline, it shows my user name just fine:

![image](https://cloud.githubusercontent.com/assets/1933277/25058505/4cb1c44c-2137-11e7-98bf-138d1f30e19d.png)

**Comment by bdpiparva** [comment]
@PredatorVI: We are working on moving ldap authentication to plugin. PRs https://github.com/gocd/gocd/pull/3356, https://github.com/gocd/gocd/pull/3289 and https://github.com/gocd/gocd/pull/3313 are opened in interest of API and SPA.

Meanwhile you can try out our [ldap authentication plugin](https://github.com/gocd/gocd-ldap-authentication-plugin) with v17.3.0. Configure `DisplayNameAttribute` with your ldap attribute and its value will be displayed on GoCD. Let us know if this solves your problem

Installation instructions are available [here](https://github.com/gocd/gocd-ldap-authentication-plugin/blob/master/README.md)

> Note: Password encryption in authconfig profile is not supported in 17.3.0

**Comment by bdpiparva** [comment]
Closing since this is already implemented in [gocd-ldap-authentication-plugin](https://github.com/gocd/gocd-ldap-authentication-plugin).
