### ISSUE TITLE
Improvements to Config Repo Implementations

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5792]
##### Issue Type

- Feature enhancement

##### Summary

Following are some scenarios where we can improve the user experience

1. Today if there is a merge conflict occurs due to 
   * Resources not available in GoCD - e.g environments, elastic profiles, this leads to an error. Once these are created in the cruise-config.xml, the user would still have to do a dummy commit on the config repo, for us to parse it. While we might not be able to do a validation while each resource is created, it would make sense to provide an option to force a re-validation of the config repo for a known commit.

   * Pipeline Dependency not fulfilled

2. Change in plugin configuration: For e.g, if the user adds a file pattern on the plugin settings and this leads to no pipelines. If the user changes this configuration, they are still required to make a dummy commit to the repo. This causes a not so good getting started to experience and restricts users to try out configuration options.

* NOTE will add to this issue and keep it as a placeholder for improvements. Related epic https://github.com/gocd/gocd/issues/5175

**Comment by ankitsri11** [comment]
@adityasood I tried adding this config-repo https://github.com/tomzo/gocd-json-config-example without adding `up42` pipeline. I got below merge error:

![screenshot 2019-02-05 at 13 32 04](https://user-images.githubusercontent.com/6838313/52305788-d76bdd80-294a-11e9-8c16-750f6511f3c0.png)

But once I added `up42` pipeline, I could see all the config-repo pipelines on the dashboard and started to build. However, the merge error didn't go away. We might need to look into that.

Another thing, I noticed as per the config-repo environment file (https://github.com/tomzo/gocd-json-config-example/blob/master/dev.goenvironment.json), `up42` pipeline needs to belong to `dev ` environment but adding `up42` pipeline after adding config-repo, I get below error.

![config-repo](https://user-images.githubusercontent.com/6838313/52306062-9de7a200-294b-11e9-8545-afcd1eb33e14.gif)

Error in the go-server.log:

```
2019-02-05 13:40:17,138 ERROR [qtp632249781-26] Rails:-2 -
2019-02-05 13:40:17,139 ERROR [qtp632249781-26] Rails:-2 - Java::JavaLang::NullPointerException ():
2019-02-05 13:40:17,139 ERROR [qtp632249781-26] Rails:-2 -
2019-02-05 13:40:17,139 ERROR [qtp632249781-26] Rails:-2 - com.thoughtworks.go.server.service.EntityHashingService.md5ForEntity(com/thoughtworks/go/server/service/EntityHashingService.java:109)
java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:455)
org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:316)
RUBY.load_existing_environment(app/controllers/environments_controller.rb:108)
org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:525)
org.jruby.RubyBasicObject.send(org/jruby/RubyBasicObject.java:1752)
org.jruby.RubyKernel.send(org/jruby/RubyKernel.java:2182)
org.jruby.RubyKernel$INVOKER$s$send.call(org/jruby/RubyKernel$INVOKER$s$send.gen)
private.tmp.gocd.go_minus_server_minus_19_dot_1_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.callbacks.invokeOther1:send(private/tmp/gocd/go_minus_server_minus_19_dot_1_dot_0/work/jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_/webapp/WEB_minus_INF/rails/gems/jruby/$2_dot_5_dot_0/gems/activesupport_minus_5_dot_2_dot_1/lib/active_support/gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:426)
private.tmp.gocd.go_minus_server_minus_19_dot_1_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.callbacks.block in make_lambda(gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:426)
org.jruby.RubyProc.call(org/jruby/RubyProc.java:286)
org.jruby.RubyProc.call(org/jruby/RubyProc.java:266)
org.jruby.RubyProc$INVOKER$i$0$0$call.call(org/jruby/RubyProc$INVOKER$i$0$0$call.gen)
private.tmp.gocd.go_minus_server_minus_19_dot_1_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.callbacks.invokeOther1:call(private/tmp/gocd/go_minus_server_minus_19_dot_1_dot_0/work/jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_/webapp/WEB_minus_INF/rails/gems/jruby/$2_dot_5_dot_0/gems/activesupport_minus_5_dot_2_dot_1/lib/active_support/gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:179)
private.tmp.gocd.go_minus_server_minus_19_dot_1_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.callbacks.block in halting_and_conditional(gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:179)
org.jruby.RubyProc.call(org/jruby/RubyProc.java:286)
org.jruby.RubyProc.call(org/jruby/RubyProc.java:266)
org.jruby.RubyProc$INVOKER$i$0$0$call.call(org/jruby/RubyProc$INVOKER$i$0$0$call.gen)
private.tmp.gocd.go_minus_server_minus_19_dot_1_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.abstract_controller.callbacks.invokeOther0:call(private/tmp/gocd/go_minus_server_minus_19_dot_1_dot_0/work/jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_/webapp/WEB_minus_INF/rails/gems/jruby/$2_dot_5_dot_0/gems/actionpack_minus_5_dot_2_dot_1/lib/abstract_controller/gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:34)
private.tmp.gocd.go_minus_server_minus_19_dot_1_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.abstract_controller.callbacks.block in Callbacks(gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:34)
org.jruby.RubyProc.call(org/jruby/RubyProc.java:286)
org.jruby.RubyProc.call(org/jruby/RubyProc.java:266)
org.jruby.RubyProc$INVOKER$i$0$0$call.call(org/jruby/RubyProc$INVOKER$i$0$0$call.gen)
private.tmp.gocd.go_minus_server_minus_19_dot_1_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.callbacks.invokeOther9:call(private/tmp/gocd/go_minus_server_minus_19_dot_1_dot_0/work/jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_/webapp/WEB_minus_INF/rails/gems/jruby/$2_dot_5_dot_0/gems/activesupport_minus_5_dot_2_dot_1/lib/active_support/gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:180)
private.tmp.gocd.go_minus_server_minus_19_dot_1_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.callbacks.block in halting_and_conditional(gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:180)
org.jruby.RubyProc.call(org/jruby/RubyProc.java:286)
org.jruby.RubyProc.call(org/jruby/RubyProc.java:266)
org.jruby.RubyProc$INVOKER$i$0$0$call.call(org/jruby/RubyProc$INVOKER$i$0$0$call.gen)
private.tmp.gocd.go_minus_server_minus_19_dot_1_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.callbacks.invokeOther0:call(private/tmp/gocd/go_minus_server_minus_19_dot_1_dot_0/work/jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_/webapp/WEB_minus_INF/rails/gems/jruby/$2_dot_5_dot_0/gems/activesupport_minus_5_dot_2_dot_1/lib/active_support/gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513)
private.tmp.gocd.go_minus_server_minus_19_dot_1_dot_0.work.jetty_minus_0_dot_0_dot_0_dot_0_minus_8153_minus_cruise_dot_war_minus__go_minus_any_minus_.webapp.WEB_minus_INF.rails.gems.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.callbacks.block in invoke_before(gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513)
org.jruby.RubyArray.each(org/jruby/RubyArray.java:1801)
```

**Comment by ankitsri11** [comment]
Above environment page error goes away after a commit to config-repo.

**Comment by ibnc** [comment]
>    * Resources not available in GoCD - e.g environments, elastic profiles, this leads to an error. Once these are created in the cruise-config.xml, the user would still have to do a dummy commit on the config repo, for us to parse it. While we might not be able to do a validation while each resource is created, it would make sense to provide an option to force a re-validation of the config repo for a known commit.
>    * Pipeline Dependency not fulfilled

To clarify, are we essentially wanting a force update/parse? If so, then do we want this functionality embedded in the refresh button on the config repositories page?

**Comment by arvindsv** [comment]
From what @maheshp told me: Once the config is "fixed" by a change in the XML, the server health message goes away, but the error continues to show in the config repositories page. He said: "[this is relevant](https://github.com/gocd/gocd/blob/ec391c6d13460a341229baced584eba9bb01e76b/server/src/main/java/com/thoughtworks/go/config/ConfigReposMaterialParseResultManager.java#L47) and might need to be cleaned up. Ideally, there is one single source of truth. In this case, the method linked above seems to do something wrong".

Don't know if that helps, @ibnc.

**Comment by maheshp** [comment]
@ibnc I have fixed the issue #2 mentioned in this ticket - https://github.com/gocd/gocd/pull/5816

**Comment by ibnc** [comment]
Issue one has been resolved.

**Comment by maheshp** [comment]
@rajiesh I was unable to reproduce the issue mentioned by @ankitsri11 https://github.com/gocd/gocd/issues/5792#issuecomment-460815117

**Comment by rajiesh** [comment]
@ibnc One more scenario to be taken care of by his PR https://github.com/gocd/gocd/pull/5843 in order to fix the issue one on this issue. In case of users with multiple config repositories defined when there are multiple parse errors, fixing the server side issue of one config repo does not resolve the parse error.

Steps to reproduce:

- Create 2 config repositories say `CR1` and `CR2` with repos as `repo-1` and `repo-2`
- Commit a pipeline config to `repo-1` with invalid upstream pipeline, say name as `upstream-pipeline`
- Wait for the error on `CR1` for invalid upstream pipeline
- Now commit another pipeline config to `repo-2` with invalid encrypted value in one of its environment variables
- Wait for the error to show up on `CR2`
- Now create a pipeline `upstream-pipeline` from GoCD server
- The error on `CR1` doesn't go away
- Only after fixing the issue in `CR2` both errors goes away

cc: @maheshp

**Comment by arvindsv** [comment]
Let's also move away from the server health messages as the source of truth, please (if they are). They're not meant for that. Some central location, updated by all config repo parsers should be used, imo.

**Comment by maheshp** [comment]
@rajiesh #5911 has fixes for the issue https://github.com/gocd/gocd/issues/5792#issuecomment-465845347

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8639-9ba73d561b80d9d4e20dbf903aaeb3d29fcd3ab4)
